/* Generated By:JavaCC: Do not edit this line. ExemploTDSConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExemploTDSConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ACHAVES = 5;
  /** RegularExpression Id. */
  int FCHAVES = 6;
  /** RegularExpression Id. */
  int VOID = 7;
  /** RegularExpression Id. */
  int CHAR = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int APAR = 10;
  /** RegularExpression Id. */
  int FPAR = 11;
  /** RegularExpression Id. */
  int VIRG = 12;
  /** RegularExpression Id. */
  int ID = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "\"Void\"",
    "\"Char\"",
    "\"Int\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<ID>",
  };

}
